Music Commands
mgylabs/mulgyeol-mkbot pull request #25
Opened 2020-12-30 14:57 UTC by minhyungk

## Summary of the Pull Request
Music commands implemented. 
Command list:

- //pause - Pauses the song that is playing
- //play - Plays the keyword searched or plays the song in queue
- //queue - Shows songs in queue
- //search - Searches music in youtube
- //skip - Skips the song that is playing and plays the next song in queue
- //stop - Stops player

## References
Discord.py
Youtube_dl

## PR Checklist
* [ ] Closes #19 
* [ ] [Changelog entry](https://github.com/mgylabs/mulgyeol-mkbot/tree/master/changelogs)

### Testing
* [ ] [Tested in packaged application](https://github.com/mgylabs/mulgyeol-mkbot/wiki/How-to-Contribute#testing-in-packaged-application)

### Dependency Changes
* [ ] Labeled as `dependencies`
* [ ] [Validated hook files](https://github.com/mgylabs/mulgyeol-mkbot/wiki/How-to-Contribute#add-hook-files)

## Detailed Description of the Pull Request / Additional comments
This pull request implements music playing commands that allows users to play music using MK bot.
Users can use the different commands offered by this pull request to take control of the music player. 

The music play function has been created using the **youtube-dl** library, and **ffmpeg**. 
The songs crawled by requests module is stored as a **Song** class, which the player stores songs requested by users in a list _song_list_, and stores the queue in variable _songQueue_ inside the **Music** Class. 

The detailed explanation of commands are in below.

- **//play**

```
Plays the keyword searched or plays the song in queue

//play "keyword"
//play
//p "keyword"
//p

Searches the keyword in Youtube and puts it in queue
If there is no keyword inputted and the player isn't playing anything, it starts the player
```

- **//pause**

```
Pauses the song that is playing

//pause
//pp

Cannot pause the player if the player is already paused
```

- **//skip**
```
Skips the song that is playing and plays the next song in queue

        //skip
        //ss
```

- **//stop**

```
Stops Player

//stop

```
- **//queue**

```
Shows songs in queue

//queue
//q

```
- **//search**

```
Searches music in youtube
//search "keyword"
//s "keyword"

Shows 5 candidates that you can choose using emotes

```
## To Be Updated
Subcommands, youtube playlist playing function, and auto-play functions will be updated in the future.

2020-12-30 15:54 UTC, MycroftKang requested changes

2020-12-30 15:54 UTC, MycroftKang commented on src/bot/core/music.py
> +                    "https://www.youtube.com/results?search_query=" + song)
```python
import aiohttp
async with session.get("https://www.youtube.com/results?search_query=" + song) as r:
    if r.status == 200:
        text = await r.text()
```
For performance reasons we no longer use `requests`. Please change all `requests` to `aiohttp`.

2020-12-30 15:54 UTC, MycroftKang commented on src/bot/core/music.py
> +        //ss
```suggestion
        {commandPrefix}skip
        {commandPrefix}ss
```
Please use `{commandPrefix}` instead of arbitrary prefix in all help docs...

2020-12-30 15:54 UTC, MycroftKang commented on src/bot/core/music.py
> +                song_list[self.songQueue].url, download=False)
```suggestion
           loop = asyncio.get_event_loop()
           data = await loop.run_in_executor(None, lambda: ytdl.extract_info(song_list[self.songQueue].url, download=False))
```
Consider running in an asyncio event loop. Functions that involve network communication like this must be executed asynchronously.

2020-12-30 16:03 UTC, MycroftKang commented on requirements.txt
> +youtube_dl == 2020.12.26
```suggestion
bs4==0.0.1
youtube_dl==2020.12.26
```

2020-12-30 17:11 UTC, MycroftKang requested changes

2020-12-31 06:08 UTC, MycroftKang requested changes

2020-12-31 06:08 UTC, MycroftKang commented on src/bot/core/music.py
> +                song_list.append(Song.addSong(title, song))
This code is not syntactically correct.

2020-12-31 06:08 UTC, MycroftKang commented on src/bot/core/music.py
> +            song_list.append(Song.addSong(title, song))
This code is not syntactically correct.

2021-01-01 03:43 UTC, MycroftKang requested changes

2021-01-01 03:43 UTC, MycroftKang commented on src/bot/core/music.py
> +                client_session = aiohttp.ClientSession(raise_for_status=True)
```suggestion
                async with aiohttp.ClientSession(raise_for_status=True) as session:
```

2021-01-01 03:43 UTC, MycroftKang commented on src/bot/core/music.py
> +                client_session = aiohttp.ClientSession(raise_for_status=True)
```suggestion
                async with aiohttp.ClientSession(raise_for_status=True) as session:
```

2021-01-01 03:43 UTC, MycroftKang commented on src/bot/core/music.py
> +                time.sleep(timeout)
It seems that this has not been fixed yet...

2021-01-01 03:43 UTC, MycroftKang commented on src/bot/core/music.py
> +                    pass
```suggestion
                fut.result()
                self.updatePlayer(ctx, song_list, songQueue)
```
We should not do these `try: ... except:`, because it hides errors and would make things difficult to debug.

2021-01-01 14:11 UTC, minhyungk commented on src/bot/core/music.py
> +                    pass
Excepting try - except cycle raises error

2021-01-01 14:12 UTC, minhyungk commented on src/bot/core/music.py
> +                client_session = aiohttp.ClientSession(raise_for_status=True)
This raises error in build and test for some reason

2021-01-01 14:12 UTC, minhyungk commented on src/bot/core/music.py
> +                client_session = aiohttp.ClientSession(raise_for_status=True)
This raises error in build and test for some reason

2021-01-01 14:23 UTC, MycroftKang commented on src/bot/core/music.py
> +                client_session = aiohttp.ClientSession(raise_for_status=True)
@minhyungk This is an indentation error. We just need to add an indented block.

2021-01-01 14:25 UTC, MycroftKang commented on src/bot/core/music.py
> +                time.sleep(timeout)
@minhyungk We should use `asyncio.sleep` instead of `time.sleep` for performance reasons.

2021-01-01 15:55 UTC, minhyungk commented
@MycroftKang All checks have been passed. Start merging?

2021-01-01 16:03 UTC, MycroftKang approved these changes

2021-01-01 16:14 UTC, minhyungk commented
@MycroftKang

2021-01-01 16:14 UTC, MycroftKang approved these changes
LGTM! 🎉

2021-01-01 16:21 UTC, merged