{commandPrefix}skip bug, {commandPrefix}play "url" bug fix
mgylabs/mulgyeol-mkbot pull request #29
Opened 2021-01-04 12:46 UTC by minhyungk

## Summary of the Pull Request

After song queue has ended, {commandPrefix}skip only lets user to play the next song
=> //play now performs this function

{commandPrefix}play "url" raises 'NoneType' error
=> Song().addSong() fixed
## References

## PR Checklist

- [ ] Closes #26  
- [ ] [Changelog entry](https://github.com/mgylabs/mulgyeol-mkbot/tree/master/changelogs)

### Testing

- [ ] [Tested in packaged application](https://github.com/mgylabs/mulgyeol-mkbot/wiki/How-to-Contribute#testing-in-packaged-application)

### Dependency Changes

- [ ] Labeled as `dependencies`
- [ ] [Validated hook files](https://github.com/mgylabs/mulgyeol-mkbot/wiki/How-to-Contribute#add-hook-files)

## Detailed Description of the Pull Request / Additional comments

2021-01-04 14:13 UTC, MycroftKang requested changes

2021-01-04 14:13 UTC, MycroftKang commented on src/bot/core/music.py
> +        if song == tuple():
```suggestion
        if len(song) == 0:
```

2021-01-05 08:59 UTC, minhyungk commented on src/bot/core/music.py
> +        if song == tuple():
@MycroftKang resolved

2021-01-05 09:37 UTC, MycroftKang approved these changes

2021-01-05 09:39 UTC, merged